# Common configuration shared between all applications
configserver:
    name: Docker Coolybot Registry
    status: Connected to the Coolybot Registry running in Docker

coolybot:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded

eureka:
    client:
        service-url:
            defaultZone: http://admin:${coolybot.registry.password}@localhost:8761/eureka/
